objects = {'Activities': 'Activities',
    'Account':'Account',
'ActionPlan__c':'Plan d''action',
'AnnualTrendOfExistingBusiness__c':'Tendance annuelle de l''embarqué',
'Asset':'Asset',
'AssetLoan__c':'Prêt de matériel',
'BusinessPlanDetail__c':'Business Plan - Détail',
'BusinessPlan__c':'Business Plan',
'Calendar__c':'Calendrier',
'Campaign':'Campaign',
'CampaignMember':'CampaignMember',
'Case':'Case',
'Contact':'Contact',
'Cost__c':'Cout',
'Event':'Activities',
'InvoiceProject__c':'Projet de facturation',
'Lead':'Lead',
'Leave__c':'Congé',
'ManagementProcess__c':'Processus de management',
'Mission__c':'Mission',
'NegociatedRate__c':'Tarif',
'Network__c':'Cercle d''influence',
'Offering_Project__c':'Association Offre / Projet',
'Offering__c':'Offre',
'Opportunity':'Opportunity',
'Opportunity_Offering__c':'Association Offre / Opportunité',
'Product2':'Product2',
'Profil__c':'Profil',
'Project__c':'Projet',
'RecruitingProcessStage__c':'Etape',
'RecruitmentProcess__c':'Processus de recrutement',
'RelationHistory__c':'Historique Relations',
'SalesAsset_Offering__c':'Association Offre / Asset',
'SalesAsset__c':'Consulting IP',
'School__c':'Ecole',
'Staffing__c':'Staffing',
'Task':'Activities'

}